version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name:  ruantang-patent-mysql # 启动的实例名称
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init/test:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络
  redis:
    image: redis:7.2-alpine
    container_name: ruantang-patent-redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
#  rabbitmq:
#    image: rabbitmq:3.12.6-management # 支持管理面板的消息队列
#    container_name: yuoj-rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672" # RabbitMQ Dashboard 端口
#    volumes:
#      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化
#    networks:
#      - mynetwork
  nacos:
    image: nacos/nacos-server:v2.5.1-slim
    container_name: ruantang-patent-nacos
    hostname: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区

  nginx:
    image: nginx:stable-alpine
    container_name: ruantang-patent-nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html # 您可以手动复制前端文件到这个目录
      - ./nginx/ssl/console:/etc/nginx/ssl/console:ro # 挂载证书
    networks:
      - mynetwork
    restart: always
networks:
  mynetwork:
