spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: host.docker.internal:8848 # Docker专用访问宿主机的地址
#      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: ${nacos.namespace:default-namespace-id}  # 使用动态配置
      config:
        namespace: ${nacos.namespace:default-namespace-id}  # 使用动态配置
        group: DEFAULT_GROUP
        file-extension: yaml  # 关键配置，指定加载yaml格式
        refresh-enabled: true  # 启用配置动态刷新
#        encode: UTF-8
  config:
    import: optional:nacos:${spring.application.name}-${env}.yaml  # 使用动态配置
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000

logging:
  level:
    com.alibaba.nacos: trace

# 定义动态配置的默认值
nacos:
  namespace: ab2acd52-3d5b-4b57-b101-45f3a466d135  # 开发环境的namespace ID

env: dev  # 定义环境标识