server:
  port: 9000

spring:
  config:
    import: optional:nacos:${spring.application.name}.yaml
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway

logging:
  level:
    com.alibaba.nacos: debug
