#应用服务WEB访问端口
server:
  port: 9600

http:
log-request-details: true

#应用名称
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/ruantang_patent_info?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis本地服务器地址，注意要开启redis服务，即那个redis-server.exe
    host: 127.0.0.1
    # Redis服务器端口,默认为6379.若有改动按改动后的来
    port: 6379
    #Redis服务器连接密码，默认为空，若有设置按设置的来
    password:
    jedis:
      pool:
        # 连接池最大连接数，若为负数则表示没有任何限制
        max-active: 8
        # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8


#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.ruantang.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # cloud
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        #如果是public就不用填写了
        namespace:
        server-addr: 127.0.0.1:8848

debug: true



secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /auth/login
      - /auth/register
      - /user/info
      - /auth/logout
      - /minio/upload
